despliegueD/webServer/app/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField,TextAreaField, BooleanField,DateField,IntegerField
from wtforms.validators import DataRequired, Email, Length
from flask_wtf.file import FileField, FileRequired

class ConcursoForm(FlaskForm):
    id = IntegerField('id')
    nombre = StringField('Nombre', validators=[Length(max=128)])
    imagen = FileField('Imagen o Banner', render_kw={'placeholder': 'Imagen o Banner'})
    url = StringField('Url', validators=[Length(max=128)])
    valor = StringField('Valor', validators=[Length(max=128)])
    fechaInicio = DateField('Fecha Inicio')
    fechaFin = DateField('Fecha Finalizacióm')
    guion = TextAreaField('Guion', validators=[Length(max=128)])
    recomendaciones = TextAreaField('recomendaciones', validators=[Length(max=128)])
    submit = SubmitField('Enviar')

despliegueD/webServer/app/admin/__init__.py
from flask import Blueprint

admin_bp = Blueprint('admin', __name__, template_folder='templates')

from . import routes

despliegueD/webServer/app/admin/routes.py
from flask import render_template, redirect, url_for, request,send_file
from flask_login import login_required, current_user
from datetime import datetime
from werkzeug.utils import secure_filename
import os
from app.models import Concurso, Participante
from . import admin_bp
from .forms import ConcursoForm
from .service import deleteAudioAPI
from app.utilidadesDynamo import *
from collections import namedtuple
from os.path import exists


@admin_bp.route("/admin/concurso/", methods=['GET', 'POST'], defaults={'concurso_id': None})
@admin_bp.route("/admin/concurso/<int:concurso_id>/", methods=['GET', 'POST','PUT'])
@login_required
def concurso_form(concurso_id): 
    form = ConcursoForm()
    if form.validate_on_submit():
        nombre = form.nombre.data
        path_imagen = secure_filename(form.imagen.data.filename)
        form.imagen.data.save("app/static/images_concurso/" + path_imagen)
        url = form.url.data
        valor = form.valor.data
        fechaInicio = form.fechaInicio.data
        fechaFin = form.fechaFin.data
        guion = form.guion.data
        recomendaciones = form.recomendaciones.data
        fechaCreacion = datetime.now()
        # Inserta el concurso en Dynamo
        concurso = insertarConcurso(user_id=current_user.id
                        ,nombre=nombre
                        ,imagen=path_imagen
                        ,url=url
                        ,valor=valor
                        ,fechaInicio=fechaInicio.strftime('%Y-%m-%d')
                        ,fechaFin=fechaFin.strftime('%Y-%m-%d')
                        ,guion=guion
                        ,recomendaciones=recomendaciones
                        ,fechaCreacion=fechaCreacion.strftime('%Y-%m-%d-%H:%M:%S'))
        return redirect(url_for('public.index'))
    return render_template("concurso_form.html", form=form)
 
@admin_bp.route("/concursoDelete/<string:url_concurso>/", methods=['GET', 'POST'])
def concurso_delete(url_concurso):
    concurso = traerInfoConcurso(url_concurso)
    concurso["PK"] = concurso["PK"].replace("CON#","")
    # TODO : Eliminar voces almacenadas en S3
    """
    participantes = Participante.get_paths_Concurso_id(concurso_id)
   	    
    for k in participantes:
        print(k.path_audio)
        deleteAudioAPI(k.path_audio.split("."))
    """

    os.remove("app/static/images_concurso/{}".format(concurso["imagen"]))
    # Eliminar concurso en Dynamo
    eliminarConcurso(concurso["PK"])
    return redirect(url_for('public.index'))

@admin_bp.route("/concursoupdate/<string:url_concurso>/", methods=['GET', 'POST'])   
def concurso_update(url_concurso):
    concurso = traerInfoConcurso(url_concurso)
    if concurso:
        # Formatear campos para que puedan ser mostrados en el form
        concurso["fechaInicio"] = datetime.strptime(concurso["fechaInicio"],'%Y-%m-%d')
        concurso["fechaFin"] = datetime.strptime(concurso["fechaFin"],'%Y-%m-%d')
        concurso["url"] = concurso["url_concurso"]
        concurso["PK"] = concurso["PK"].replace("CON#","")
        # Crear objeto a partir de diccionario
        concurso_obj = namedtuple('Struct', concurso.keys())(*concurso.values())
        form = ConcursoForm(obj=concurso_obj)

        if request.method == 'POST' and form.validate():
            try:
                path_imagen = secure_filename(form.imagen.data.filename)
                form.imagen.data.save("app/static/images_concurso/" + path_imagen)
                # Actualiza el concurso en Dynamo
                response = actualizarConcursoForm(uid=concurso["PK"]
                                ,nombre=form.nombre.data
                                ,imagen=path_imagen
                                ,url=form.url.data
                                ,valor=form.valor.data
                                ,fechaInicio=form.fechaInicio.data.strftime('%Y-%m-%d')
                                ,fechaFin=form.fechaFin.data.strftime('%Y-%m-%d')
                                ,guion=form.guion.data
                                ,recomendaciones=form.recomendaciones.data)
            except:
                # Actualiza el concurso en Dynamo sin la imagen
                response = actualizarConcursoFormNoImg(uid=concurso["PK"]
                                ,nombre=form.nombre.data
                                ,url=form.url.data
                                ,valor=form.valor.data
                                ,fechaInicio=form.fechaInicio.data.strftime('%Y-%m-%d')
                                ,fechaFin=form.fechaFin.data.strftime('%Y-%m-%d')
                                ,guion=form.guion.data
                                ,recomendaciones=form.recomendaciones.data)
            return redirect(url_for('public.index')) 
        return render_template('concurso_form.html', form=form)

@admin_bp.route("/participanteDelete/<string:url_concurso>/<string:participante_id>/") 
def participante_delete(url_concurso,participante_id):
    participante = traerInfoParticipante(url_concurso,participante_id)
    if exists("app/static/AudioFilesDestiny/{}".format(participante["path_audio"])):
        os.remove("app/static/AudioFilesDestiny/{}".format(participante["path_audio"]))
    if exists("app/static/AudioFilesOrigin/{}".format(participante["path_audio_origin"])):
        os.remove("app/static/AudioFilesOrigin/{}".format(participante["path_audio_origin"]))
    # Eliminar participante de DB Dynamo
    eliminarParticipante(url_concurso,participante_id)
    return redirect(url_for('public.index'))


@admin_bp.route('/participante/uploads/<path:filename>', methods=['GET', 'POST'])
def download_participante(filename):
    path = "static/AudioFilesDestiny/{}".format(filename)
    return send_file(path, as_attachment=True)

@admin_bp.route('/participante/uploads_origin/<path:filename>', methods=['GET', 'POST'])
def participante_origin_download(filename):
    path = "static/AudioFilesOrigin/{}".format(filename)
    return send_file(path, as_attachment=True)

despliegueD/webServer/app/admin/templates/concurso_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!doctype html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">



    <!-- Bootstrap core CSS -->
        <link href="/static/sytles/bootstrap.min.css" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light  navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('public.index') }}">Supervoices</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if current_user.is_anonymous %}
        </li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Iniciar sesión</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.show_signup_form') }}">Registro</a></li>
        {% else %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('public.principal') }}">Concursos</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('admin.concurso_form') }}">Nuevo Concurso</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Cerrar sesión</a></li>
                <li class="nav-item"><a class="nav-link"> Bienvenid@ {{ current_user.email }}</li>
            {% endif %}
      </ul>
      <span class="navbar-text">
        Equipo 5
      </span>
    </div>
  </div>
</nav>


{% block title %}
    {% if form.nombre.data %}
        {{ form.nombre.data }}
    {% else %}
        Nuevo Concurso
    {% endif %}
{% endblock %}
  <br>
  <br>
{% block content %}
    <link href="/static/sytles/signin.css" rel="stylesheet">
<main class="form-signin">
    <form  action="" method="post" novalidate enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <img class="mb-4" src="../../static/sytles/supervoices.png" alt="">

        <label for="form-control">Nombre concurso</label>
            {{ form.nombre(class_="form-control form-control-sm") }}
        <label for="formFile" class="form-label">Imagen ó Banner</label>
            {{ form.imagen(class_="form-control form-control-sm", type="file", id="formFile") }}
        <label for="form-control">Url</label>
            {{ form.url(class_="form-control form-control-sm") }}
        <div>
            {{ form.fechaInicio.label }}<br>
            {{ form.fechaInicio }}<br>
            {% for error in form.fechaInicio.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.fechaFin.label }}<br>
            {{ form.fechaFin }}<br>
            {% for error in form.fechaFin.errors %}<br>
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </div>
        <label for="form-control">Compensación</label>
            {{ form.valor(class_="form-control form-control-sm") }}
        <label for="form-control">Guión</label>
            {{ form.guion(class_="form-control form-control-sm") }}
        <label for="form-control">Recomendaciones</label>
            {{ form.recomendaciones(class_="form-control form-control-sm") }}
        <div>

        <br>
        <br>

        {% if form.nombre.data %}
            <input type="submit">
        {% else %}
            {{ form.submit(class_="w-100 btn btn-lg btn-primary") }}
        {% endif %}

        </div>
    </form>
</main>
{% endblock %}