tempDespliegueD/newWebServer/project/participante/models.py
from project import db
import datetime
from project.concurso.models import Concurso
from bson import ObjectId

class Participante(db.DynamicDocument):
    meta = {'collection': 'Participante'} 
    concurso=db.ReferenceField(Concurso,required=True,reverse_delete_rule=2)
    concurso_id=db.StringField(required=True)
    path_audio=db.StringField(required=True)
    nombres=db.StringField(required=True)
    apellidos=db.StringField(required=True)
    mail=db.EmailField(required=True)
    observaciones=db.StringField(required=True)
    convertido=db.BooleanField(default=False,required=True)
    fechaCreacion=db.DateTimeField(default=datetime.datetime.now(),required=True)

    def __repr__(self): 
        return "<Participantes '{}'>".format(self.mail)

    @staticmethod
    def deleteAllDocuments():
        Participante.objects.delete()
    @staticmethod
    def findByConcurso(_id):
        return Participante.objects(concurso_id=str(_id))
    def get_by_id(id):
        return Participante.objects(id=ObjectId(id)).first()

tempDespliegueD/newWebServer/project/participante/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField,TextAreaField, BooleanField,DateField,IntegerField, SelectField, EmailField
from wtforms.validators import DataRequired, Email, Length
from flask_wtf.file import FileField, FileRequired

class ParticipanteForm(FlaskForm):
    id = IntegerField('id')
    concurso_id = IntegerField('concurso')
    path_audio = FileField('Voz', validators=[FileRequired()], render_kw={'placeholder': 'Cargar Voz'})
    nombres = StringField('nombres', validators=[Length(max=128)])
    apellidos = StringField('apellidos', validators=[Length(max=128)])
    mail = EmailField('mail', validators=[DataRequired(), Email(), Length(max=128)])
    observaciones = TextAreaField('observaciones', validators=[Length(max=128)])
    convertido = StringField('convertido', validators=[Length(max=128)])
    submit = SubmitField('Enviar')

    def __init__(self,concurso):
        super().__init__()
        self.concurso_id=concurso

tempDespliegueD/newWebServer/project/participante/__init__.py
from flask import Blueprint
participantes_blueprint = Blueprint('participantes', __name__, template_folder='templates')

from . import routes

tempDespliegueD/newWebServer/project/participante/routes.py
from flask import render_template, redirect, url_for, request, flash
from datetime import datetime
from werkzeug.utils import secure_filename
from project.concurso.models import Concurso
from project.participante.models import Participante
from . import participantes_blueprint
from .forms import ParticipanteForm
import math
from .services import postAudioAPI, sendMessageSQS
from flask_login import login_required, current_user
import json
from bson import ObjectId


@participantes_blueprint.route("/")
def index():
    return render_template("principal.html")

@participantes_blueprint.route("/concursos")
def principal():
    concursos=[]
    if not current_user.is_authenticated:
        concursos = Concurso.get_all()
    else:
        concursos = Concurso.findByUsuario(str(current_user.id))
    return render_template("index.html", concursos=concursos)

@participantes_blueprint.route("/concursos/<string:url>/", defaults={"page": 1})
@participantes_blueprint.route("/concursos/<string:url>/<int:page>")
def show_concurso(page,url):
    concurso = Concurso.get_by_url(url)
    participantes = []
    number_pages = 1
    if not current_user.is_authenticated:
        participantes = Participante.objects(concurso=concurso.id,convertido=True).order_by('-fechaCreacion').paginate(page=page, per_page=20).items
        number_pages = Participante.objects(concurso=concurso.id,convertido=True).count()
    else:
        participantes = Participante.objects(concurso=concurso.id).order_by('-fechaCreacion').paginate(page=page, per_page=20).items
        number_pages = Participante.objects(concurso=concurso.id).count()

    if number_pages<= 20:
        number_pages=1
    else:
        number_pages= int(math.ceil(number_pages/20)+1)
    return render_template("concurso_view.html", concurso=concurso, voz=participantes, pages=number_pages)

@participantes_blueprint.route("/participantes/<string:participante_id>/")
@login_required
def show_participante(participante_id):
    participante = Participante.get_by_id(participante_id)
    if participante is None:
        flask.abort(404)
    return render_template("participante_view.html", participante=participante)

@participantes_blueprint.route("/public/participante/<string:concurso_id>", methods=['GET', 'POST'])
def participante_form(concurso_id):
    concurso=Concurso.get_by_url(concurso_id)
    concurso_id=str(concurso.id)
    form = ParticipanteForm(concurso_id)
    if form.validate_on_submit():
        concurso_id =form.concurso_id
        mail = form.mail.data
        path_audio = secure_filename(form.path_audio.data.filename)
        format_file=path_audio.split('.')[-1]
        form.path_audio.data.save("project/static/TempStorage/" + path_audio)
        nombres = form.nombres.data
        apellidos = form.apellidos.data
        observaciones = form.observaciones.data
        convertido = False
        fechaCreacion = datetime.now()
        participante = Participante(concurso=Concurso.get_by_id(concurso_id)
                        ,concurso_id=concurso_id
                        ,path_audio=path_audio
			            ,path_audio_origin=path_audio
                        ,nombres=nombres
                        ,apellidos=apellidos
                        ,mail=mail
                        ,observaciones=observaciones
                        ,convertido=False
                        ,fechaCreacion=fechaCreacion)
        participante.save(cascade=True)
        postAudioAPI("project/static/TempStorage/" + path_audio,str(participante.id)+'.'+format_file)
        participante.update(path_audio=str(participante.id)+'.'+format_file)
        participante.update(path_audio_origin=str(participante.id)+'.'+format_file)
        participante.save(cascade=True)
        sendMessageSQS(str(participante.id),str(participante.id)+'.'+format_file,mail,nombres)
        flash('Hemos recibido tu voz y la estamos procesando para que sea publicada en la \
                            página del concurso y pueda ser posteriormente revisada por nuestro equipo de trabajo. \
                            Tan pronto la voz quede publicada en la página del concurso te notificaremos por email.')
        return  redirect(url_for('participantes.participante_form',concurso_id=concurso.url))
    return render_template("participante_form.html", form=form)

tempDespliegueD/newWebServer/project/participante/templates/concurso_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!doctype html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">



    <!-- Bootstrap core CSS -->
        <link href="../../static/sytles/bootstrap.min.css" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light  navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('participantes.index') }}">Supervoices</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if current_user.is_anonymous %}
        </li>

            <li class="nav-item"><a class="nav-link" href="{{ url_for('users.login') }}">Iniciar sesión</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('users.show_signup_form') }}">Registro</a></li>
        {% else %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('participantes.principal') }}">Concursos</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('concurso.concurso_form') }}">Nuevo Concurso</a></li>
    		<li class="nav-item"><a class="nav-link" href="{{ url_for('participantes.participante_form',concurso_id=concurso['url']) }}">Nuevo Participante</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Cerrar sesión</a></li>
                <li class="nav-item"><a class="nav-link"> Bienvenid@ {{ current_user.email }}</li>
            {% endif %}
      </ul>
      <span class="navbar-text">
        Equipo 5
      </span>
    </div>
  </div>
</nav>

  <br>
  <br>
  <br>
  <br>
<img src="https://dqhc4frcuc82u.cloudfront.net/imagenes/{{ concurso['imagen'] }}" alt="Smiley face" width="120" height="80" style="vertical-align:middle">

  <br>
  <br>
{% block title %}{{ concurso["nombre"] }}{% endblock %}
{% block content %}

    <h1></h1>Nombre del concurso es: {{ concurso["nombre"] }}</h1></br>
    URL: {{ concurso["url"] }} </br>
    Fecha Inicio: {{ concurso["fechaInicio"] }} </br>
    Fecha Fin: {{ concurso["fechaFin"] }} </br>
    Valor: {{ concurso["valor"] }} </br>
    Guion: {{ concurso["guion"] }} </br>
    Recomendaciones: {{ concurso["recomendaciones"] }} </br>
    Fecha Creación: {{ concurso["fechaCreacion"] }} </br>
    
    {% if current_user.is_anonymous %}
      <li ><a href="{{ url_for('participantes.participante_form',concurso_id=concurso['url']) }}">Nuevo Participante</a></li>
    {% endif %}

    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Concurso participantes</title>
  </head>
  <body>
    <br>
        <table class="table table-dark table-striped">
            <thead>
            {% if current_user.is_anonymous %}
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Email</th>
                <th scope="col">Fecha</th>
                <th scope="col">Estado de la voz</th>
                <th scope="col">Voz</th>
            </tr>
            </thead>
            <tbody>
                {% for participantes in voz %}
                <tr class="row-even">
                <td><p>{{participantes.id}}</p></td>
                    <td><p>{{participantes["mail"]}}</p></td>
                    <td><p>{{  participantes["fechaCreacion"] }}</p></td>
                    {% if participantes["convertido"] == True %}
                        <td><p>Convertido</p></td>
                    {% else %}
                        <td><p>En proceso</p></td>
                    {% endif %}
                    <td><p><p><ul><audio src="https://dqhc4frcuc82u.cloudfront.net/convertidos/{{ participantes['path_audio'] }}" controls> <source src="https://dqhc4frcuc82u.cloudfront.net/convertidos/{{ participantes['path_audio'] }}" type="audio/mp3" ></audio>
                     </ul></p>
                    </div></p></td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                <th scope="col">ID</th>
                <th scope="col">Email</th>
                <th scope="col">Fecha</th>
                <th scope="col">Estado de la voz</th>
                <th scope="col">Voz</th>
                <th scope="col">Descargar original</th>
                <th scope="col">Descargar convertida</th>
                <th scope="col">Detalle participante</th>
                <th scope="col">Eliminar</th>
                </tr>
                </thead>
                {% for participantes in voz %}
                    <tr class="row-even">
                    <td><p>{{participantes.id}}</p></td>
                    <td><p>{{participantes["mail"]}}</p></td>
                    <td><p>{{  participantes["fechaCreacion"] }}</p></td>
                    {% if participantes["convertido"] == True %}
                        <td><p>Convertido</p></td>
                    {% else %}
                        <td><p>En proceso</p></td>
                    {% endif %}
                    <td><p><p><ul><audio src="https://dqhc4frcuc82u.cloudfront.net/convertidos/{{ participantes['path_audio'] }}" controls> <source src="https://dqhc4frcuc82u.cloudfront.net/convertidos/{{ participantes['path_audio'] }}" type="audio/mp3" ></audio></ul></p></p></td>
                     <td><p><p><a href="https://dqhc4frcuc82u.cloudfront.net/originales/{{ participantes['path_audio_origin'] }}" download>Descargar original</a></p></p></td>
                     <td><p><p><a href="https://dqhc4frcuc82u.cloudfront.net/convertidos/{{ participantes['path_audio'] }}" download>Descargar convertida</a></p></p></td>
                        <td><p><p><a href="{{ url_for('participantes.show_participante', url_concurso=concurso['url'] ,participante_id=participantes.id | string()) }}">Ver detalle</a></p></p></td>
                        <td><p><p><a href="{{ url_for('concurso.participante_delete', url_concurso=concurso['url'] ,participante_id=participantes.id | string()) }}">Eliminar</a></p></p></td>
                    </tr>
                {% endfor %}
            {% endif %}
            </tbody>
            </table>
  <div class="table-responsive">
  <table class="table">
  </table>
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
      {% for pages in range(1,pages) %}
           <li class="page-item"><a class="page-link" href="{{ url_for( 'participantes.show_concurso', url=concurso['url'], page=pages) }}">{{ pages }}</a></li>
      {% endfor %}



  </ul>
</nav>

{% endblock %}
</body>
</html>

tempDespliegueD/newWebServer/project/participante/templates/index.html
{% extends "base_template.html" %}
{% block title %}Proyecto 1 - Grupo 05{% endblock %}
{% block content %}
    <br>
    <br>
    <br>

    <ul>
    {% if current_user.is_anonymous %}
        {% for concurso in concursos %}
        <li>
            <a href="{{ url_for('participantes.show_concurso', url=concurso['url']) }}">{{ concurso["nombre"] }}</a>
        </li>
        {% endfor %}
    {% else %}
        {% for concurso in concursos %}
        <li>
            <a href="{{ url_for('participantes.show_concurso',url=concurso['url']) }}">{{ concurso["nombre"] }}</a>
            <a href="{{ url_for('concurso.concurso_delete',concurso_id=concurso.id | string()) }}">Eliminar</a>
            <a href="{{ url_for('concurso.concurso_update',concurso_id=concurso.id | string()) }}">Actualizar</a>
        </li>
    {% endfor %}
    {% endif %}
    </ul>
{% endblock %}

tempDespliegueD/newWebServer/project/participante/templates/participante_form.html
{% extends "base_template.html" %}
{% block title %}Login{% endblock %}
{% block content %}

<link href="../../static/sytles/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="../../static/sytles/signin.css" rel="stylesheet">
<main class="form-signin">
  <form action="" method="post" novalidate enctype="multipart/form-data">
      {{ form.hidden_tag() }}
    <img class="mb-4" src="../../static/sytles/supervoices.png" alt="">

    <label for="form-control">Concurso</label><br>
        {{ form.concurso_nombre }}
    <div class="mb-3">
    <label for="formFile" class="form-label">Voz</label>
        {{ form.path_audio(class_="form-control form-control-sm", type="file", id="formFile") }}
    </div>
     <label for="form-control">Nombres</label>
       {{ form.nombres(class_="form-control form-control-sm") }}
      <label for="form-control">Apellidos</label>
        {{ form.apellidos(class_="form-control form-control-sm") }}
      <label for="form-control">Email</label>
        {{ form.mail(class_="form-control form-control-sm") }}
      <label for="form-control">Observaciones</label>
        {{ form.observaciones(class_="form-control form-control-sm", size=32) }}
        <br>
        <br>
      {{ form.submit(class_="w-100 btn btn-lg btn-primary") }}

	{% for message in get_flashed_messages() %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    .alert {
        padding: 20px;
        background-color: #f44336;
        color: white;
    }
    .alert.success {background-color: #4CAF50;}

    .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
}

    .closebtn:hover {
        color: black;
}
    </style>

<div class="alert success">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
  <strong>Proceso Exitoso!</strong> {{ message }}</div>
    {% endfor %}


  </form>
</main>
{% endblock %}

tempDespliegueD/newWebServer/project/participante/templates/participante_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ participante["nombre"] }}{% endblock %}</title>
    <!doctype html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="generator" content="Hugo 0.88.1">



    <!-- Bootstrap core CSS -->
        <link href="../../static/sytles/bootstrap.min.css" rel="stylesheet">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-light  navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('participantes.index') }}">Supervoices</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        {% if current_user.is_anonymous %}
        </li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('participantes.principal') }}">Concursos</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('users.login') }}">Iniciar sesión</a></li>
            <li class="nav-item"><a class="nav-link" href="{{ url_for('users.show_signup_form') }}">Registro</a></li>
        {% else %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('participantes.principal') }}">Concursos</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('concurso.concurso_form') }}">Nuevo Concurso</a></li>

                <li class="nav-item"><a class="nav-link" href="{{ url_for('users.logout') }}">Cerrar sesión</a></li>
                <li class="nav-item"><a class="nav-link"> Bienvenid@ {{ current_user.email }}</li>
            {% endif %}
      </ul>
      <span class="navbar-text">
        Equipo 5
      </span>
    </div>
  </div>
</nav>
</body>
</html>

<br>
<br>
<br>

{% block content %}
    <h1></h1>Nombre del participante es: {{ participante["nombres"] }} {{ participante["apellidos"] }} </h1> </br>
    Nombre concurso: {{ participante["nombre_concurso"] }} </br>
    path_audio: {{ participante["path_audio"] }} </br>
    mail: {{ participante["mail"] }} </br>
    observaciones: {{ participante["observaciones"] }} </br>
    convertido: {{ participante["convertido"] }} </br>
    fechaCreacion: {{ participante["fechaCreacion"] }} </br>

{% endblock %}

tempDespliegueD/newWebServer/project/participante/templates/principal.html
{% extends "base_template.html" %}
{% block title %}principal{% endblock %}

{% block content %}
<!-- Custom styles for this template -->
    <link href="../static/sytles/signin.css" rel="stylesheet">
    <img class="logo-centro"  src="../static/sytles/supervoices.png" alt="">
{% endblock %}