tempDespliegueD/newWebServer/project/usuario/models.py
from email.policy import default
from project import db
from bson import ObjectId
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class Usuario(db.DynamicDocument,UserMixin):
    meta = {'collection': 'Usuario'} 

    nombres=db.StringField(required=True)
    password=db.StringField(required=True)
    apellidos=db.StringField(required=True)
    email=db.EmailField(required=True)

    def __repr__(self): 
        return "<Usuario '{}'>".format(self.nombres)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


    @staticmethod
    def deleteAllDocuments():
        Usuario.objects.delete()

    @staticmethod
    def getByMailPassword(email,password):
        return Usuario.objects(email=email,password=password).first()

    @staticmethod
    def get_by_email(email):
        return Usuario.objects(email=email).first()
    
    @staticmethod
    def get_by_id(id):
        return Usuario.objects(_id=ObjectId(id)).first()
    

tempDespliegueD/newWebServer/project/usuario/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField,TextAreaField, BooleanField,DateField,IntegerField, EmailField
from wtforms.validators import DataRequired, Email, Length

class SignupForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('confirmar contraseña', validators=[DataRequired()])
    nombres = StringField('Nombres', validators=[DataRequired()])
    apellidos = StringField('Apellidos', validators=[DataRequired()])
    email = EmailField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Registrar')



class LoginForm(FlaskForm):
    email = EmailField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Recuérdame')
    submit = SubmitField('Login')

tempDespliegueD/newWebServer/project/usuario/__init__.py
from flask import Blueprint
users_blueprint = Blueprint('users', __name__, template_folder='templates')

from . import routes

tempDespliegueD/newWebServer/project/usuario/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import current_user, login_user, logout_user
from werkzeug.urls import url_parse
import pickle

from project import login_manager
from . import users_blueprint
from .forms import SignupForm, LoginForm
from project.usuario.models import Usuario

@users_blueprint.route("/signup/", methods=["GET", "POST"])
def show_signup_form():
    if current_user.is_authenticated:
        return redirect(url_for('participantes.index'))
    form = SignupForm()
    error = None
    if form.validate_on_submit():
        email = form.email.data
        nombres = form.nombres.data
        apellidos = form.apellidos.data
        password = form.password.data
        confirmar_password = form.password2.data
        if password == confirmar_password:
            error = 'La contraseña de verificación no coincide.'
            user = Usuario.get_by_email(email)
            if user is not None:
                flash(f'El email {email} ya se encuentra registrado')
            else:
                user = Usuario(email=email, nombres=nombres, apellidos=apellidos)
                user.set_password(password)
                user.save()
                print(user)
                login_user(user, remember=True)
                next_page = request.args.get('next', None)
                if not next_page or url_parse(next_page).netloc != '':
                    next_page = url_for('participantes.index')
                    return redirect(next_page)
        else:
            flash('La contraseña no coincide')
    return render_template("signup_form.html", form=form, error=error)

@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('participantes.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Usuario.get_by_email(form.email.data)
        if user is not None and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            next_page = request.args.get('next')
            if not next_page or url_parse(next_page).netloc != '':
                next_page = url_for('participantes.principal')
            return redirect(next_page)
    return render_template('login_form.html', form=form)

    
@users_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('participantes.index'))


@login_manager.user_loader
def load_user(user_id):
    user_obj = Usuario.get_by_id(user_id)
    return user_obj

tempDespliegueD/newWebServer/project/usuario/templates/login_form.html
{% extends "base_template.html" %}
{% block title %}Login{% endblock %}
{% block content %}

<link href="../static/sytles/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="../static/sytles/signin.css" rel="stylesheet">
<main class="form-signin">
  <form action="" method="post" novalidate>
      {{ form.hidden_tag() }}
    <img class="mb-4" src="../static/sytles/supervoices.png" alt="">

      <label for="form-control">Email</label>
        {{ form.email(class_="form-control form-control-sm") }}
      <label for="form-control">Contraseña</label>
        {{ form.password(class_="form-control form-control-sm") }}
    <div class="checkbox mb-3">
      <label>
        {{ form.remember_me(class_="checkbox") }} {{ form.remember_me.label }}
      </label>
    </div>
      {{ form.submit(class_="w-100 btn btn-lg btn-primary ") }}

   <div>¿No tienes cuenta? <a href="{{ url_for('users.show_signup_form') }}">Regístrate</a></div>
    <p class="mt-5 mb-3 text-muted" align="center">&copy; Equipo 5 2022</p>

  </form>
</main>
{% endblock %}

tempDespliegueD/newWebServer/project/usuario/templates/signup_form.html
{% extends "base_template.html" %}
{% block title %}Login{% endblock %}
{% block content %}

<link href="../static/sytles/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="../static/sytles/signin.css" rel="stylesheet">
<main class="form-signin">
  <form action="" method="post" novalidate>
      {{ form.hidden_tag() }}
    <img class="mb-4" src="../static/sytles/supervoices.png" alt="">

      <label for="form-control">Nombres</label>
        {{ form.nombres(class_="form-control form-control-sm") }}
      <label for="form-control">Apellidos</label>
        {{ form.apellidos(class_="form-control form-control-sm") }}
      <label for="form-control">Email</label>
        {{ form.email(class_="form-control form-control-sm") }}
      <label for="form-control">Contraseña</label>
        {{ form.password(class_="form-control form-control-sm", size=32) }}
      <label for="form-control">Confirmar Contraseña</label>
        {{ form.password2(class_="form-control form-control-sm", size=32) }}

      {{ form.submit(class_="w-100 btn btn-lg btn-primary") }}

   <div>¿ya tienes cuenta? <a href="{{ url_for('users.login') }}">Iniciar Sesión</a></div>
    <p class="mt-5 mb-3 text-muted" align="center">&copy; Equipo 5 2022</p>

  {% for message in get_flashed_messages() %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
    .alert {
        padding: 20px;
        background-color: #f44336;
        color: white;
    }

    .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
}

    .closebtn:hover {
        color: black;
}
    </style>

<div class="alert">
  <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
  <strong>Error</strong> {{ message }}</div>
    {% endfor %}


  </form>
</main>
{% endblock %}